version: '3.3'

services:
  postgres:
    container_name: cosign-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cosign
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped

  pgadmin:
    container_name: cosign-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: .
    depends_on:
      - "postgres"
    environment:
      SECRET_KEY: test_key
      DB_USER: postgres
      PASSWORD: postgres
      DB_NAME: cosign
      DB_HOST: cosign-postgres
      DB_PORT: 5432
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin: